services:
  backend:
    build: .
    command: npm start
    ports:
      - "10000:10000"
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /usr/src/app/backend/src

        - action: sync+restart
          path: ./public
          target: /usr/src/app/backend/public

        - action: rebuild
          path: ./package.json

        - action: rebuild
          path: ./package-lock.json

        - action: rebuild
          path: ./Dockerfile

        - action: rebuild
          path: ./.dockerignore

        - action: rebuild
          path: ./.env

  worker:
    build: .
    command: npm run worker
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /usr/src/app/backend/src

        - action: rebuild
          path: ./package.json

        - action: rebuild
          path: ./package-lock.json

        - action: rebuild
          path: ./Dockerfile

        - action: rebuild
          path: ./.dockerignore

        - action: rebuild
          path: ./.env